
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 05 11:57:25 CET 2015
//----------------------------------------------------

package PECL2;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TK_RETURN = 8;
  public static final int TK_BOOL = 21;
  public static final int TK_CLOSEPARENT = 15;
  public static final int TK_RESTA = 11;
  public static final int TK_PROGRAM = 10;
  public static final int TK_IGUAL = 12;
  public static final int TK_SEMI = 17;
  public static final int TK_OPENPARENT = 14;
  public static final int TK_NUMERO = 22;
  public static final int TK_SUMA = 18;
  public static final int EOF = 0;
  public static final int TK_TRUE = 7;
  public static final int TK_FUNCTION = 3;
  public static final int TK_FUNCID = 20;
  public static final int TK_BEGIN = 2;
  public static final int TK_VARCDEL = 5;
  public static final int TK_INTEGER = 6;
  public static final int error = 1;
  public static final int TK_COMA = 16;
  public static final int TK_ASIGNACION = 13;
  public static final int TK_END = 4;
  public static final int TK_FALSE = 9;
  public static final int TK_ID = 19;
}

