/* The following code was generated by JFlex 1.4.3 on 12/5/15 11:35 AM */


package  PECL2;

import java.io.*;
import java.util.*;
import java_cup.runtime.*;




/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/5/15 11:35 AM from the specification file
 * <tt>/Users/luisparada1/Documents/workspace/PECL2_2/src/PECL2/Lexico.lex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  9, 18,  0,  9,  7,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     9, 17, 17, 17,  3, 17, 17, 17, 12, 13, 17,  5, 10,  4,  0,  8, 
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6, 17, 11, 16, 14, 15, 17, 
    17,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 17, 17, 17, 17,  2, 
    17,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 17, 17, 17, 17,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\1\14\1\6"+
    "\1\2\1\15\1\0\1\16\1\0\1\5\1\17\1\20"+
    "\1\5\1\0\1\15\1\16\1\21\1\0\1\15\1\0"+
    "\1\22\1\21\1\15";

  private static int [] zzUnpackAction() {
    int [] result = new int[37];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\0\0\23\0\46\0\71\0\114\0\137\0\162"+
    "\0\205\0\23\0\230\0\23\0\23\0\23\0\23\0\23"+
    "\0\71\0\23\0\46\0\253\0\71\0\276\0\321\0\162"+
    "\0\23\0\23\0\205\0\344\0\253\0\276\0\367\0\u010a"+
    "\0\u011d\0\344\0\23\0\367\0\u011d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[37];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\3\5"+
    "\1\22\24\0\2\23\3\0\1\23\15\0\1\24\1\25"+
    "\3\0\1\25\1\0\1\25\5\0\4\25\2\0\1\26"+
    "\1\27\1\0\3\27\1\0\1\27\1\0\2\27\2\0"+
    "\4\27\7\0\1\30\10\0\1\31\1\32\10\0\1\30"+
    "\15\0\1\24\1\25\3\0\1\33\1\0\1\25\5\0"+
    "\4\25\2\0\1\24\1\25\3\0\1\25\1\0\1\34"+
    "\5\0\4\25\2\0\2\35\3\0\1\35\15\0\2\36"+
    "\3\0\1\36\15\0\1\37\1\27\1\0\3\27\1\0"+
    "\1\27\1\0\2\27\2\0\4\27\1\0\1\40\1\41"+
    "\1\42\3\40\1\42\1\43\1\42\5\40\4\42\1\43"+
    "\1\0\2\44\3\0\1\44\14\0\7\40\1\43\12\40"+
    "\1\43\1\40\2\45\3\40\1\45\1\43\12\40\1\43";

  private static int [] zzUnpackTrans() {
    int [] result = new int[304];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\6\1\1\11\1\1\5\11\1\1\1\11"+
    "\2\1\1\0\1\1\1\0\1\1\2\11\1\1\1\0"+
    "\3\1\1\0\1\1\1\0\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[37];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

private Symbol sym(int type)
	{
		return sym(type, yytext());
	}

	private Symbol sym(int type, Object value)
	{
		return new Symbol(type, yyline, yycolumn, value);
	}
	 static int palabrasreservadas=0;
	 static int numeros=0;
	 static int identificador=0;
	 static int errores=0;
	 static int booleanos=0;
	 static int funciones=0;
	 static int comentarios= 0;
	 static String mensaje="";
	 public static int lexico=0;
	 static ArrayList<String> FuncionesToken = new ArrayList<String>();
	 
	
	
	
	
	
	public static void main (String argv[])throws java.io.IOException {
			for(int i=0; i<argv.length ; i++){
			File fis=new File(argv[4]); 
        	String nombre= fis.getName();
 			int tamaño = nombre.length();
 			
        	if (nombre.startsWith(".prog", tamaño-5))
        	{
        	FileInputStream realFile =new FileInputStream(fis.getAbsolutePath());   
        		
				System.out.println();
				System.out.println( "Comenzando el análisis de su archivo: "+ nombre);
				System.out.println();
				
				
				Yylex yy = new Yylex(realFile);   
				while (yy.yylength() != -1) ;  
				
				} 
			else{
			System.out.println();
			System.out.println( "Comenzando el análisis de su archivo: "+ nombre);
		
			System.out.println( "Su Archivo:  " +nombre+ " no es compatible");
			
				}		
			}
		}
		public  static void reporte(){
			System.out.println(""); 
			System.out.println("Estadísticas"); 
			System.out.println("------------"); 
			System.out.println(""); 
			System.out.println("Numero de palabras reservadas: " +palabrasreservadas); 
			System.out.println("Numeros:" + numeros); 
			System.out.println("Booleanos: " + booleanos);
		   
		    
			int i=0;
			int size = FuncionesToken.size();
			System.out.print("Funciones: "+size+ " (");
				while(i<FuncionesToken.size()){
				System.out.print(FuncionesToken.get(i)+ "," );
				i++;
			
			}
			System.out.print(")");
			System.out.println();
			System.out.println("Identificadores: " + identificador);
			palabrasreservadas=0;
	 		numeros=0;
	 		identificador=0;
	 		errores=0;
	 		booleanos=0;
	 		funciones=0;
	 		comentarios= 0;
	 		mensaje="";
	 		FuncionesToken.removeAll(FuncionesToken);
		}
		
		public static  void Agregar (String token){
			if (!FuncionesToken.contains(token)){
				FuncionesToken.add(token);
			}
		}
		
		
		
		public static int  Implicito(String token)
		{
			String nuevo = token.toUpperCase();
			
			switch(nuevo)
			{
				case "PROGRAM": palabrasreservadas++;
					 			return 1;
					 			
				case "RETURN": palabrasreservadas++;
							   return 2;
							   
				case "TRUE":   palabrasreservadas++; 
							   booleanos++;
							   return 3;
							   
				case "FALSE":  palabrasreservadas++; 
							   booleanos++;
							   return 4;
							   
				case "INTEGER": palabrasreservadas++; 	
								return 5;
				
				case "BOOLEAN": palabrasreservadas++;
								return 6;
				
				case "FUNCTION": palabrasreservadas++;
								 return 7;
								 
				case "BEGIN": 	palabrasreservadas++;
								return 8;
								
				case "END":		palabrasreservadas++;
								return 9;
				
				case "VARDECL": palabrasreservadas++;
								return 10;
			
				default:   return 11;
						 
			
			
			}
		
			
		}
		
		
		
		
		public  void Error (int opcion )
		{
			
			Integer linea=1;
			Integer columna=1;
			columna = columna+yycolumn;
			linea = linea+yyline;
				switch (opcion)
			{
				case 0:  System.out.println("Error lexico  en la linea: " +linea+" "+ "columna: " +columna+ " Identificador Erroneo: "+ "'" +yytext()+"'");
						 lexico=lexico + 1;
						 break;
				
			
				case 1: System.out.println("Error lexico  en la linea: " +linea+" "+ "columna: " +columna+ " Funcion Erronea: "+ "'" +yytext()+"'");
						lexico=lexico + 1;
						break;
			
				}
		}
		
		
		



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 6: 
          { /*	Salto de linea*/
          }
        case 19: break;
        case 14: 
          { funciones++; Agregar(yytext()); 
											return new Symbol(sym.TK_FUNCID,yyline + 1,yycolumn + 1,yytext());
          }
        case 20: break;
        case 2: 
          { switch(Implicito(yytext()))
											{
												case 1:  return new Symbol(sym.TK_PROGRAM,yyline + 1,yycolumn + 1,yytext());
					 											
					 			
												case 2:  return new Symbol(sym.TK_RETURN,yyline + 1,yycolumn + 1,yytext());
							 						    
							   
												case 3:  return new Symbol(sym.TK_TRUE,yyline + 1,yycolumn + 1,yytext());
							  						 
							   
												case 4:  return new Symbol(sym.TK_FALSE,yyline + 1,yycolumn + 1,yytext());
													  	
							   
												case 5:  return new Symbol(sym.TK_INTEGER,yyline + 1,yycolumn + 1,yytext() );
				
												case 6:  
												
												
												return new Symbol(sym.TK_BOOL,yyline + 1,yycolumn + 1,yytext() );
				
												case 7:  return new Symbol(sym.TK_FUNCTION,yyline + 1,yycolumn + 1,yytext());
													 
								 
												case 8:  return new Symbol(sym.TK_BEGIN,yyline + 1,yycolumn + 1,yytext());
													
								
												case 9:	 return new Symbol(sym.TK_END,yyline + 1,yycolumn + 1,yytext());
													
					
												case 10:  return new Symbol(sym.TK_VARCDEL,yyline + 1,yycolumn + 1,yytext());
											

												default: 
														 
														 
														 return new Symbol (sym.TK_ID,yyline + 1,yycolumn + 1,yytext() );
						 						}
          }
        case 21: break;
        case 9: 
          { return new Symbol(sym.TK_SEMI,yyline + 1,yycolumn + 1,yytext());
          }
        case 22: break;
        case 18: 
          { /* Comentarios */
          }
        case 23: break;
        case 11: 
          { return new Symbol (sym.TK_CLOSEPARENT,yyline + 1,yycolumn + 1,yytext() );
          }
        case 24: break;
        case 16: 
          { System.out.println("Error en la linea: " +yyline+" "+ "columna: " +yycolumn+  "'" +yytext()+"'");
          }
        case 25: break;
        case 10: 
          { return new Symbol (sym.TK_OPENPARENT,yyline + 1,yycolumn + 1,yytext() );
          }
        case 26: break;
        case 4: 
          { return new Symbol(sym.TK_SUMA,yyline + 1,yycolumn + 1,yytext() );
          }
        case 27: break;
        case 13: 
          { Error(0);
          }
        case 28: break;
        case 8: 
          { return new Symbol(sym.TK_COMA,yyline + 1,yycolumn + 1,yytext());
          }
        case 29: break;
        case 3: 
          { return new Symbol(sym.TK_RESTA,yyline + 1,yycolumn + 1,yytext() );
          }
        case 30: break;
        case 12: 
          { return new Symbol(sym.TK_IGUAL,yyline + 1,yycolumn + 1,yytext() );
          }
        case 31: break;
        case 15: 
          { return new Symbol(sym.TK_ASIGNACION,yyline + 1,yycolumn + 1,yytext() );
          }
        case 32: break;
        case 5: 
          { numeros++; 
											
											 return new Symbol (sym.TK_NUMERO, yyline,yycolumn, new Integer(yytext()));
          }
        case 33: break;
        case 7: 
          { /*	Espacio*/
          }
        case 34: break;
        case 17: 
          { Error(1);
          }
        case 35: break;
        case 1: 
          { System.out.println("Error en la linea: " +(yyline + 1) +" "+ "columna: " +(yycolumn + 1)+ " Error lexico "+ "'" +yytext()+"'");
																																lexico= lexico + 1;
          }
        case 36: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
